spring:
  profiles:
    active:
      - local
    include:
      - oauth
      - secret
      - db
      - redis
custom:
  default-profile:
    https://e7.pngegg.com/pngimages/1000/665/png-clipart-computer-icons-profile-s-free-angle-sphere.png
  front-local-url: http://localhost:5173
  front-server-url: https://second.codesquad-project.site
